# MATEMÁTICAS PARA IA : Raúl Capellán Fernández

## PRÁCTICA 1

In [1]:
import numpy as np
from numpy import linalg as LA
from timeit import default_timer as timer

In [2]:
def pseudorandom_matrix(n):
    
    # Matriz aleatoria con valores comprendidos entre 0 y 1.
    A=np.random.rand(n, n)

    # Hago simétrica la matriz aleatoria generada anteriormente.
    # Garantiza que la matriz es diagonalizable.
    for i in range(0, n):
        for j in range(i+1, n):
            A[i, j]=A[j, i]
    # Calculo la suma de los elementos de cada fila y me quedo con la máxima.      
    maxrow=0
    for i in range(0, n):
        row=0
        for j in range(0, n):
            row=row+A[i, j]
        if row>maxrow:
            maxrow=row

    # Divido todas las entradas de la matriz por el valor anterior.
    # Garantiza que los valores propios se encuentran entre 0 y 1.
    for i in range(0, n):
        for j in range(0, n):
            A[i, j]=A[i, j]/maxrow

    return A

### Ejercicio 1
 - Apartado A:

In [16]:
u = np.array([1, 2])
v = np.array([5, 6])

In [17]:
v_norm = np.sqrt(sum(v**2))
proyeccionUV = (np.dot(u, v)/v_norm**2)*v
print("La proyeccion de u sobre v es:", proyeccionUV) 

La proyeccion de u sobre v es: [1.39344262 1.67213115]


In [20]:
ortogonal = u@v
print(ortogonal)
if(ortogonal == 0):
    print('Son vectores ortogonales')
else:
    print('No son vectores ortogonales')

17
No son vectores ortogonales


In [22]:
pEscalarProOrto = proyeccionUV * ortogonal
print(pEscalarProOrto)

[23.68852459 28.42622951]


El producto de estos dos valores va a ser un vector del tamaño del vector proyeccion. 

Al no ser el producto escalar igual a cero, podemos afirmar que no se corresponden con un vector ortogonal.

Se puede decir que la posicion relativa de ambos vecctores no es la misma.

- Apartado B: Multiplicar matrices

In [5]:
def multiplicaMatriz(a,b):
    fA = np.shape(a)[0]
    cA = np.shape(a)[1]
    
    fB = np.shape(b)[0]
    cB = np.shape(b)[1]

    if(cA != fB):
        print('No son compatibles no se pueden multiplicar')
        return("No se pueden multiplicar")

    result = np.zeros((fA,cB))

    for i in range(fA):
        for j in range(cB):
            for k in range(cA):
                result[i][j] = result[i][j] + a[i][k] * b[k][j]
    return result

In [6]:
a= [[3,3,3], [2,2,2]]
b= [[3,3,3], [2,2,2],[4,4,4]]

print(multiplicaMatriz(a,b))

[[27. 27. 27.]
 [18. 18. 18.]]


- Apartado C: calcular determinante

In [7]:
def calculaDeterminante(a, total=0):
    indices = list(range(len(a)))
     
    if len(a) == 2 and len(a[0]) == 2:
        val = a[0][0] * a[1][1] - a[1][0] * a[0][1]
        return val
 
    for i in indices: 
        copyA = a.copy() 
        copyA = copyA[1:]
        altura = len(copyA) 
 
        for j in range(altura): 
            copyA[j] = copyA[j][0:i] + copyA[j][i+1:] 
 
        signo = (-1) ** (i % 2)
        subDet = calculaDeterminante(copyA)
        total += signo * a[0][i] * subDet 
 
    return total


In [8]:
b= [[3,3,3], [2,4,10],[123,4,4]]
print(calculaDeterminante(b))

2142


### Ejercicio 2
- Apartado A: A^k

In [9]:
def matrizExponente(matriz,aux,k):
    if(k == 1):
        print(matriz)
        return
    
    matriz = multiplicaMatriz(matriz,aux)
    matrizExponente(matriz,aux,k-1)

In [10]:
matrizExponente(b,b,2)

[[ 384.   33.   51.]
 [1244.   62.   86.]
 [ 869.  401.  425.]]


- Apartado B: A^k Diagonal

In [11]:
def matrizExponenteDiagonal(matriz,k):
    valPropios, vecPropios = LA.eig(matriz)

    p = vecPropios
    pInversa = LA.inv(p)

    mDiagonal = np.zeros((np.shape(matriz)[0], np.shape(matriz)[1]),int)
    np.fill_diagonal(mDiagonal,k)

    result = multiplicaMatriz(p,mDiagonal)
    result = multiplicaMatriz(result,pInversa)
    print(result)

In [12]:
matrizExponenteDiagonal(b,2)

[[ 1.13317723  0.18268861  0.07250635]
 [ 5.37671081  0.86682277 -0.44974092]
 [ 0.          0.          2.        ]]


/Users/cp/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:17: ComplexWarning: Casting complex values to real discards the imaginary part


- Apartado C: tiempos de ejecucion

In [13]:
matriz = pseudorandom_matrix(50)

In [14]:
start = timer()
print("Tiempo de ejecucion A^k Diagonal")
matrizExponenteDiagonal(matriz,100)
end = timer()
print(end - start)
print("----------------------\n",end - start,"Segundos\n----------------------\n")

Tiempo de ejecucion A^k Diagonal
[[ 1.00000000e+02  9.29117894e-15  1.51545443e-14 ... -5.95010152e-15
  -2.98094882e-14 -1.66533454e-15]
 [ 2.32799890e-15  1.00000000e+02  3.44169138e-15 ...  7.63278329e-16
  -1.34892097e-14 -3.55271368e-15]
 [ 9.93649607e-15 -1.11022302e-16  1.00000000e+02 ... -2.16493490e-15
   2.30926389e-14 -9.76996262e-15]
 ...
 [ 8.27463098e-15 -4.48946436e-15  3.22519789e-14 ...  1.00000000e+02
   3.49720253e-15  3.88578059e-15]
 [ 3.60822483e-16 -7.79931675e-15  3.99680289e-15 ... -5.32907052e-15
   1.00000000e+02  1.33226763e-15]
 [ 5.44009282e-15  2.18713936e-14  1.42108547e-14 ... -3.21964677e-15
  -9.32587341e-15  1.00000000e+02]]
0.588769077
----------------------
 0.588769077 Segundos
----------------------



In [15]:
start = timer()
print("Tiempo de ejecucion A^k")
matrizExponente(matriz,matriz,100)
end = timer()
print(end - start)
print("----------------------\n",end - start,"Segundos\n----------------------\n")

Tiempo de ejecucion A^k
[[2.13968496e-10 1.91464877e-10 2.02996628e-10 ... 1.53986770e-10
  2.24438337e-10 1.46280567e-10]
 [1.91464877e-10 1.71328022e-10 1.81646949e-10 ... 1.37791584e-10
  2.00833578e-10 1.30895862e-10]
 [2.02996628e-10 1.81646949e-10 1.92587374e-10 ... 1.46090643e-10
  2.12929597e-10 1.38779597e-10]
 ...
 [1.53986770e-10 1.37791584e-10 1.46090643e-10 ... 1.10819704e-10
  1.61521604e-10 1.05273778e-10]
 [2.24438337e-10 2.00833578e-10 2.12929597e-10 ... 1.61521604e-10
  2.35420485e-10 1.53438323e-10]
 [1.46280567e-10 1.30895862e-10 1.38779597e-10 ... 1.05273778e-10
  1.53438323e-10 1.00005396e-10]]
22.708069998
----------------------
 22.708069998 Segundos
----------------------

